

name: 'DBT'
version: '1.0.0'
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'DBT_staging') }}"  # ✅ Must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]


models:
  my_project:
    staging:
      +schema: staging
      +alias: stg_Iris  # Optional, to explicitly control table names
    odp:
      +schema: odp
      +alias: odp_Iris  # Optional, to explicitly control table names
