name: 'DBT'
version: '1.0.0'
config-version: 2

profile: 'DBT'  # This must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

models:
  DBT:
    staging:
      +schema: staging  # ✅ Ensure schema applies correctly
    odp:
      +schema: odp  # ✅ Prevents automatic dataset creation like odp_odp   

# -- If your model uses materialized: table, dbt drops and recreates the table every time.
# -- If your model uses materialized: view, dbt replaces the view.
# -- ✅ Fix: Use materialized: incremental instead.
