name: 'DBT'
version: '1.0.0'
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'DBT_staging') }}"  # ✅ Must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

models:
  DBT:
    staging:
      +schema: "{{ env_var('STAGING_DATASET_NAME', 'staging') }}"
    odp:
      +schema: "{{ env_var('ODP_DATASET_NAME', 'odp') }}"
    
