

name: 'DBT'
version: '1.0.0'
config-version: 2

profile: "{{ env_var('DBT_PROFILE', 'DBT_staging') }}"  # ✅ Must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]


# models:
#   DBT:
#     staging:
#       +schema: staging
#       +enabled: "{{ target.profile == 'DBT_staging' }}"  # Enable only for DBT_staging
#     odp:
#       +schema: odp
#       +enabled: "{{ target.profile == 'DBT_odp' }}"  # Enable only for DBT_odp

