name: 'DBT'
version: '1.0.0'
config-version: 2

profile: 'DBT'  # ✅ Must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

models:
  DBT:
    landing:
      +schema: landing  # ✅ Ensure schema applies correctly
      +materialized: view  # ✅ Apply default materialization for staging
    staging:
      +schema: staging  # ✅ Ensure schema applies correctly
      +materialized: incremental  # ✅ Apply default materialization for staging
    odp:
      +schema: odp  # ✅ Prevents automatic dataset creation like odp_odp
      +materialized: incremental  # ✅ Set incremental as default for ODP
