name: 'DBT'
version: '1.0.0'
config-version: 2

profile: 'DBT'  # ✅ Must match the profile name in profiles.yml

model-paths: ["models"]
# seed-paths: ["seeds"]
# test-paths: ["tests"]
# analysis-paths: ["analyses"]
# macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]

# models:
#   DBT:
#     odp:
#       +schema: "odp"
#       +materialized: incremental  # ✅ Set incremental as default for ODP
#     staging:
#       +schema: "staging"
#       +materialized: incremental  # ✅ Apply default materialization for staging

