name: 'DBT'
version: '1.0.0'
config-version: 2

profile: 'DBT'  # Matches profiles.yml

model-paths: ["models"]
# Uncomment the following if applicable:
# seed-paths: ["seeds"]  # Define paths for seed files
# test-paths: ["tests"]  # Define paths for test files
# analysis-paths: ["analyses"]  # Define paths for analysis files
macro-paths: ["macros"]
# snapshot-paths: ["snapshots"]  # Define paths for snapshot files

models:
  DBT:
    staging:
      +schema: "{{ env_var('DBT_STAGING_DATASET', 'staging') }}"  # Added a more consistent env_var key
      +materialized: "incremental"
    odp:
      +schema: "{{ env_var('DBT_FINAL_DATASET', 'odp') }}"  # Added a more consistent env_var key
      +materialized: "incremental"
