DBT:
  target: odp_final
  outputs:
    odp_final:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('ODP_DATASET_NAME') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
    staging:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('STAGING_DATASET_NAME') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"

    landing:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('LANDING_DATASET_NAME') }}"
      threads: 4
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
