DBT:
  target: odp  # ✅ Default target (change as needed)
  outputs:
    odp:  # ✅ ODP target
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: odp  # ✅ Ensures dbt uses the "odp" dataset
      threads: 1  # ✅ Adjust based on performance needs
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"

    staging:  # ✅ Staging target
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging  # ✅ Ensures dbt uses the "staging" dataset
      threads: 1
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
