DBT:
  target: dev  # ✅ Default target (change as needed)
  outputs:
    dev:  # ✅ ODP target
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: odp  # ✅ Ensures dbt uses the "odp" dataset
      threads: 1  # ✅ Adjust based on performance needs
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"


