DBT:
  target: odp  # ✅ Matches the target name used in dbt commands
  outputs:
    odp:  # ✅ Ensure consistency with the target name
      type: bigquery
      method: service-account 
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: odp  # ✅ Only "odp", ensuring dbt doesn't create unwanted datasets
      threads: 1  # ✅ Recommended: Increase threads for performance
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"

  outputs:
    staging:  # ✅ Ensure consistency with the target name
      type: bigquery
      method: service-account 
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: staging  # ✅ Only "odp", ensuring dbt doesn't create unwanted datasets
      threads: 1  # ✅ Recommended: Increase threads for performance
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"




