DBT:
  target: odp
  outputs:
    odp:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "odp"
      threads: 4
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"
    staging:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "staging"
      threads: 4
      keyfile: "{{ env_var('GCP_CREDENTIALS') }}"

