name: DBT_for_Bigquery_Using_Github_Actions

on:
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 9:30 IST [4:30 AM UST]
  workflow_dispatch:  # Allows manual triggering

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "LANDING_DATASET_NAME=${{ secrets.LANDING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "STAGING_DATASET_NAME=${{ secrets.STAGING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "ODP_DATASET_NAME=${{ secrets.ODP_DATASET_NAME }}" >> $GITHUB_ENV
          echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/service_account.json
          echo "GCP_CREDENTIALS=/tmp/service_account.json" >> $GITHUB_ENV

      - name: Install Python and dbt
        run: |
          pip install dbt-bigquery

      - name: Run dbt Debug (Check Connection)
        run: dbt debug --profiles-dir ./profile

      - name: Run dbt Models
        run: dbt run --profiles-dir ./profile --target odp_final

      - name: Run dbt Tests
        run: dbt test --profiles-dir ./profile --target odp_final

      - name: Clean Up
        run: rm -f /tmp/service_account.json
