name: DBT_for_BigQuery_Using_GitHub_Actions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 9:30 AM IST (4:30 AM UTC)
  workflow_dispatch:

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "LANDING_DATASET_NAME=${{ secrets.LANDING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "STAGING_DATASET_NAME=${{ secrets.STAGING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "ODP_DATASET_NAME=${{ secrets.ODP_DATASET_NAME }}" >> $GITHUB_ENV
          echo '${{ secrets.GCP_CREDENTIALS }}' > $HOME/service_account.json
          echo "GCP_CREDENTIALS=$HOME/service_account.json" >> $GITHUB_ENV

      - name: Install Python and dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery

      - name: Run dbt Debug (Check Connection)
        run: dbt debug --profiles-dir . --target odp  # Ensure 'odp' target is used

      - name: Run dbt Compile
        run: dbt compile --profiles-dir . --target odp

      - name: Run dbt Models (Landing → Staging)
        run: dbt run --profiles-dir . --select staging --target odp  # Run staging models

      - name: Run dbt Models (Staging → ODP)
        run: dbt run --profiles-dir . --select odp --target odp  # Run ODP models

      - name: Run dbt Tests
        run: dbt test --profiles-dir . --target odp

      - name: Clean Up
        run: rm -f $HOME/service_account.json
