name: DBT_MultiProfile_BigQuery_Pipeline  # ✅ Updated workflow name for clarity

on:
  push:
    branches:
      - main  # Change if using a different branch
  schedule:
    - cron: '30 4 * * *'  # Runs every day at 9:30 IST [4:30 AM UTC]
  workflow_dispatch:  # Allows manual triggering

jobs:
  dbt-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Environment Variables
        run: |
          echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "LANDING_DATASET_NAME=${{ secrets.LANDING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "STAGING_DATASET_NAME=${{ secrets.STAGING_DATASET_NAME }}" >> $GITHUB_ENV
          echo "ODP_DATASET_NAME=${{ secrets.ODP_DATASET_NAME }}" >> $GITHUB_ENV
          echo '${{ secrets.GCP_CREDENTIALS }}' > $HOME/service_account.json
          echo "GCP_CREDENTIALS=$HOME/service_account.json" >> $GITHUB_ENV

      - name: Install Python and dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-bigquery

      # ✅ Running dbt for Staging Profile
      - name: Run dbt Debug (Staging)
        run: dbt debug --profiles-dir ./profile --target dev --profile DBT_staging

      - name: Run dbt Compile (Staging)
        run: dbt compile --profiles-dir ./profile --target dev --profile DBT_staging

      - name: Run dbt Run (Staging)
        run: dbt run --profiles-dir ./profile --target dev --profile DBT_staging

      - name: Run dbt Test (Staging)
        run: dbt test --profiles-dir ./profile --target dev --profile DBT_staging

      # ✅ Running dbt for ODP Profile
      - name: Run dbt Debug (ODP)
        run: dbt debug --profiles-dir ./profile --target dev --profile DBT_odp

      - name: Run dbt Compile (ODP)
        run: dbt compile --profiles-dir ./profile --target dev --profile DBT_odp

      - name: Run dbt Run (ODP)
        run: dbt run --profiles-dir ./profile --target dev --profile DBT_odp

      - name: Run dbt Test (ODP)
        run: dbt test --profiles-dir ./profile --target dev --profile DBT_odp

      - name: Clean Up
        run: rm -f $HOME/service_account.json
