version: 2

sources:
  - name: landing
    database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
    schema: landing  # ✅ Use schema as a string, not inside quotes unless needed
    tables:
      - name: Iris
        description: "Raw Iris dataset from the landing area"
