version: 2

sources:
  - name: landing # Just a name
    database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
    schema: landing  # ✅ Use schema as a string, not inside quotes unless needed
    tables:
      - name: Iris
        description: "Raw Data"
  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
    schema: staging  # ✅ Use schema as a string, not inside quotes unless needed
    tables:
      - name: stg_Iris
        description: "Intermediate Tables"

  - name: odp
    database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
    schema: odp  # ✅ Use schema as a string, not inside quotes unless needed
    tables:
      - name: odp_Iris
        description: "Final Table"
