# version: 2

# sources:
#   - name: landing # Just a name
#     database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
#     schema: landing  # ✅ Use schema as a string, not inside quotes unless needed
#     tables:
#       - name: Iris
#         description: "Raw Data"
#       - name: Consent_Removal
#         description: "All Consents"


#   - name: staging # Just a name
#     database: "{{ env_var('GCP_PROJECT_ID') }}"  # Your GCP project ID
#     schema: staging  # ✅ Use schema as a string, not inside quotes unless needed
#     tables:
#       - name: stg_Iris
#         description: "Raw Data"

#   - name: odp
#     database: "{{ env_var('GCP_PROJECT_ID') }}"
#     schema: odp
#     tables:
#       - name: odp_Iris
#         description: "Processed ODP Data"

version: 2

sources:
  - name: landing
    database: "{{ env_var('GCP_PROJECT_ID') }}"  
    schema: "{{ env_var('LANDING_DATASET_NAME') }}"  # ✅ Use environment variable
    tables:
      - name: Iris
        description: "Raw Data"
      - name: Consent_Removal
        description: "All Consents"

  - name: staging
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('STAGING_DATASET_NAME') }}"  # ✅ Use environment variable
    tables:
      - name: stg_Iris
        description: "Processed Staging Data"


